
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace Hydra
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.LED7R led7r;
        Gadgeteer.Modules.GHIElectronics.Joystick joystick;
        Gadgeteer.Modules.OpenSource.XBee coordinator;
        Gadgeteer.Modules.OpenSource.XBee router;
        Gadgeteer.Modules.OpenSource.XBee endDevice;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            coordinator = new GTM.OpenSource.XBee(4);
		
            router = new GTM.OpenSource.XBee(6);
		
            endDevice = new GTM.OpenSource.XBee(7);
		
            joystick = new GTM.GHIElectronics.Joystick(13);
		
            led7r = new GTM.GHIElectronics.LED7R(14);

        }
    }
}
